// Code generated by "stringer -type=ConditionType -output=condition_type_string.go"; DO NOT EDIT.

package condition

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EQUAL-0]
	_ = x[NOT_EQUAL-1]
	_ = x[GREATER_THAN-2]
	_ = x[LESS_THAN-3]
	_ = x[GREATER_THAN_OR_EQUAL-4]
	_ = x[LESS_THAN_OR_EQUAL-5]
	_ = x[CONTAINS-6]
	_ = x[NOT_CONTAINS-7]
	_ = x[IS_TRUE-8]
	_ = x[IS_FALSE-9]
	_ = x[MATCHES_EXPRESSION-10]
	_ = x[WITHIN_RANGE-11]
	_ = x[IS_EMPTY-12]
	_ = x[NOT_EMPTY-13]
	_ = x[MATCH-14]
	_ = x[ANY_MATCH-15]
	_ = x[NO_MATCH-16]
	_ = x[IS_SUBSET-17]
	_ = x[NO_DUPLICATES-18]
	_ = x[CONTAINS_ANY-19]
	_ = x[CONTAINS_ALL-20]
	_ = x[DATE_BEFORE-21]
	_ = x[DATE_AFTER-22]
	_ = x[DATE_UP_TO-23]
	_ = x[DATE_FROM-24]
	_ = x[VALID_DATE-25]
	_ = x[SAME_DATE-26]
	_ = x[NOT_SAME_DATE-27]
	_ = x[DATE_WITHIN_INTERVAL-28]
	_ = x[DATE_IN_FUTURE-29]
	_ = x[UNKNOWN-30]
}

const _ConditionType_name = "EQUALNOT_EQUALGREATER_THANLESS_THANGREATER_THAN_OR_EQUALLESS_THAN_OR_EQUALCONTAINSNOT_CONTAINSIS_TRUEIS_FALSEMATCHES_EXPRESSIONWITHIN_RANGEIS_EMPTYNOT_EMPTYMATCHANY_MATCHNO_MATCHIS_SUBSETNO_DUPLICATESCONTAINS_ANYCONTAINS_ALLDATE_BEFOREDATE_AFTERDATE_UP_TODATE_FROMVALID_DATESAME_DATENOT_SAME_DATEDATE_WITHIN_INTERVALDATE_IN_FUTUREUNKNOWN"

var _ConditionType_index = [...]uint16{0, 5, 14, 26, 35, 56, 74, 82, 94, 101, 109, 127, 139, 147, 156, 161, 170, 178, 187, 200, 212, 224, 235, 245, 255, 264, 274, 283, 296, 316, 330, 337}

func (i ConditionType) String() string {
	if i < 0 || i >= ConditionType(len(_ConditionType_index)-1) {
		return "ConditionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConditionType_name[_ConditionType_index[i]:_ConditionType_index[i+1]]
}
